name: 'Slack Send Message'
description: 'Send message to slack and return thread id'
author: 'Team Devops'
inputs:
  channel_id:
    required: true
    description: 'add channel id'
  payload:
    required: false
    description: 'add payload send message'
  thread_ts:
    required: false
    description: 'add thread id'
  environment:
    required: true
    description: 'add name environment'
    default: 'Sandbox'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-right-circle'  
  color: 'blue'
